export interface VisualEditingConfig {
  /**
   * Unique identifier for the content document, typically the file path
   * within the content source.
   */
  objectId: string;
  /**
   * Optional base path that is prefixed to all field paths generated by the helper.
   */
  baseFieldPath?: string;
}

export interface VisualEditingHelpers {
  /**
   * Returns attributes to attach to an element that represents an entire document.
   */
  document: () => Record<string, string>;
  /**
   * Returns attributes for a single field within the document.
   */
  field: (fieldPath: string) => Record<string, string>;
  /**
   * Returns attributes for an item inside a repeater/array field.
   */
  repeaterItem: (repeaterPath: string, index: number) => Record<string, string>;
}

/**
 * Lightweight replacement for Stackbit's visualEditing helper.
 * This ensures the UI renders the data-sb-* attributes that the
 * Netlify Visual Editor uses to map DOM nodes to content fields.
 */
export function visualEditing(config: VisualEditingConfig): VisualEditingHelpers {
  const prefix = config.baseFieldPath ? `${config.baseFieldPath}.` : '';

  const withObjectId = (attrs: Record<string, string>) => ({
    'data-sb-object-id': config.objectId,
    ...attrs,
  });

  return {
    document: () => withObjectId({}),
    field: (fieldPath: string) =>
      withObjectId({
        'data-sb-field-path': `${prefix}${fieldPath}`,
      }),
    repeaterItem: (repeaterPath: string, index: number) =>
      withObjectId({
        'data-sb-field-path': `${prefix}${repeaterPath}[${index}]`,
      }),
  };
}

export interface StackbitField {
  name: string;
  type: string;
  label?: string;
  items?: StackbitField | StackbitField[];
  fields?: StackbitField[];
  required?: boolean;
  default?: unknown;
}

export interface StackbitModel {
  name: string;
  type: 'data' | 'page' | string;
  label?: string;
  fields: StackbitField[];
  filePath?: string;
  fileName?: string;
  match?: string;
}

export interface StackbitContentSource {
  name: string;
  type: string;
  path: string;
  models: StackbitModel[];
}

export interface StackbitConfig {
  stackbitVersion: string;
  contentSources: StackbitContentSource[];
}

export function defineDocumentModel(model: StackbitModel): StackbitModel {
  return model;
}

export function defineStackbitConfig(config: StackbitConfig): StackbitConfig {
  return config;
}
