import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/app/components/ui/card';
import { Badge } from '@/app/components/ui/badge';
import { Button } from '@/app/components/ui/button';
import { ArrowLeft, Phone, Clock, Calendar, User, MessageSquare, Volume2, AlertCircle } from 'lucide-react';
import { format } from 'date-fns';

interface Call {
  id: string;
  created_at: string;
  caller: string;
  status: string;
  topic: string;
  duration: number;
  is_after_hours: boolean;
  outcome?: string;
}

interface Transcript {
  id: string;
  transcript_text: string;
}

interface CallDetailProps {
  call: Call;
  transcript: Transcript | null;
  summary: string | null;
  transcriptsEnabled: boolean;
  recordingUrl: string | null;
  onBack: () => void;
}

export function CallDetail({
  call,
  transcript,
  summary,
  transcriptsEnabled,
  recordingUrl,
  onBack,
}: CallDetailProps) {
  const formatDuration = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${mins}m ${secs}s`;
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'ai_handled':
        return 'bg-success text-white';
      case 'transferred':
        return 'bg-warning text-foreground';
      case 'missed':
        return 'bg-error text-white';
      default:
        return 'bg-muted';
    }
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="sm" onClick={onBack}>
          <ArrowLeft className="size-4 mr-2" />
          Back to Calls
        </Button>
      </div>

      <div>
        <h1 className="text-3xl font-bold mb-2">Call Details</h1>
        <p className="text-muted-foreground">Complete call information and transcript</p>
      </div>

      {/* Call Overview */}
      <Card>
        <CardHeader>
          <div className="flex items-start justify-between">
            <div>
              <CardTitle className="flex items-center gap-2">
                <Phone className="size-5" />
                {call.caller}
              </CardTitle>
              <CardDescription className="mt-1">
                {format(new Date(call.created_at), 'MMMM d, yyyy • h:mm a')}
              </CardDescription>
            </div>
            <Badge className={getStatusColor(call.status)}>
              {call.status === 'ai_handled' && 'AI Handled'}
              {call.status === 'transferred' && 'Transferred'}
              {call.status === 'missed' && 'Missed'}
            </Badge>
          </div>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div className="flex items-center gap-3">
              <Clock className="size-5 text-muted-foreground" />
              <div>
                <div className="text-sm text-muted-foreground">Duration</div>
                <div className="font-medium">{formatDuration(call.duration)}</div>
              </div>
            </div>

            <div className="flex items-center gap-3">
              <MessageSquare className="size-5 text-muted-foreground" />
              <div>
                <div className="text-sm text-muted-foreground">Topic</div>
                <div className="font-medium">{call.topic}</div>
              </div>
            </div>

            <div className="flex items-center gap-3">
              <User className="size-5 text-muted-foreground" />
              <div>
                <div className="text-sm text-muted-foreground">Call Type</div>
                <div className="font-medium">
                  {call.is_after_hours ? 'After Hours' : 'Business Hours'}
                </div>
              </div>
            </div>
          </div>

          {call.outcome && (
            <div className="pt-4 border-t">
              <div className="text-sm text-muted-foreground mb-1">Outcome</div>
              <div className="font-medium">{call.outcome}</div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* AI Summary */}
      {summary && (
        <Card>
          <CardHeader>
            <CardTitle>AI Summary</CardTitle>
            <CardDescription>Automated call summary generated by AI</CardDescription>
          </CardHeader>
          <CardContent>
            <p className="text-foreground leading-relaxed">{summary}</p>
          </CardContent>
        </Card>
      )}

      {/* Call Recording */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Volume2 className="size-5" />
            Call Recording
          </CardTitle>
        </CardHeader>
        <CardContent>
          {recordingUrl ? (
            <div>
              <audio controls className="w-full" src={recordingUrl}>
                Your browser does not support the audio element.
              </audio>
              <p className="text-sm text-muted-foreground mt-2">
                Use the player above to listen to the call recording
              </p>
            </div>
          ) : (
            <div className="flex items-start gap-3 p-4 bg-muted rounded-lg">
              <AlertCircle className="size-5 text-muted-foreground shrink-0 mt-0.5" />
              <div>
                <p className="font-medium mb-1">Recording Not Available</p>
                <p className="text-sm text-muted-foreground">
                  This feature is available as an add-on — contact DineTalk support to enable call recording
                </p>
              </div>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Transcript */}
      <Card>
        <CardHeader>
          <CardTitle>Call Transcript</CardTitle>
          <CardDescription>Full conversation text</CardDescription>
        </CardHeader>
        <CardContent>
          {transcriptsEnabled ? (
            transcript ? (
              <div className="prose prose-sm max-w-none">
                <div className="bg-muted p-4 rounded-lg font-mono text-sm whitespace-pre-wrap">
                  {transcript.transcript_text}
                </div>
              </div>
            ) : (
              <div className="text-muted-foreground text-center py-4">
                No transcript available for this call
              </div>
            )
          ) : (
            <div className="flex items-start gap-3 p-4 bg-muted rounded-lg">
              <AlertCircle className="size-5 text-muted-foreground shrink-0 mt-0.5" />
              <div>
                <p className="font-medium mb-1">Transcripts Not Available</p>
                <p className="text-sm text-muted-foreground">
                  This feature is available as an add-on — contact DineTalk support to enable call transcripts
                </p>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
